### ISSUE TITLE
Overload error

### ISSUE THREAD

**Issue by stefets** [webpolis/mididings-arpeggiator#1]
~/project/mididings-arpeggiator$ python synth-studio.py
Traceback (most recent call last):
  File "synth-studio.py", line 63, in <module>
    Call(arp().setup, **arp1Args),
  File "/usr/lib/python2.7/dist-packages/mididings/overload.py", line 107, in call_overload
    return _registry[k](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mididings/overload.py", line 78, in __call__
    return call(args, kwargs, self.funcs, self.name)
  File "/usr/lib/python2.7/dist-packages/mididings/overload.py", line 61, in call
    raise TypeError(message)
TypeError: no suitable overload found for Call(*, outPort=*, outChannel=*, pattern=*, direction=*, randomVelocity=*, inChannel=*, latch=*, resolution=*), candidates are:
    Call(function)
    Call(thread)

**Comment by webpolis** [comment]
Which mididings version are you using? It seems is quite outdated

**Comment by stefets** [comment]
I run the stable version 20120419, on Ubuntu Mate 16.04 on a Raspberry pi

**Comment by webpolis** [comment]
Yep, that's the issue. This one is made for mididings 2015+rbbec99a. I will update the repository's README. 

Checkout latest changes from official repo: https://github.com/dsacre/mididings
